telegram:
  token: asd
  users: []
  declineMessage: "go away"
buttons:
  - name: name1
    row: 0
    command: "ls"
    arguments: ["-l", "-a"]
    output: true
  - name: name2
    row: 1
    command: "./test.sh"
    exitCode: true
  - name: name3
    row: 1
    command: "echo"
    arguments: ["Hello world"]
    output: true
